# Generated by Django 3.2.15 on 2022-08-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='helllo', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
